language: node_js

node_js:
  - "14"
  - "12"
env:
  - NODE_ENV=test
services:
  - mongodb
before_script:
  - mongo wildlifetest --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - npm install --include=dev
  - npm run test
after_success: npm run coverage
